Add a Staging Ground message indicator to reports on Staging Ground posts
Charcoal-SE/SmokeDetector pull request #7827
Opened 2023-06-03 19:58 UTC by Papershine

As mentioned in #7649, it would be helpful to indicate that if a post might be hidden due to being in the Staging Ground. This pull requests implements one of the suggestions of displaying that information in the message report. Sample:

> [ SmokeDetector | MS ] No whitespace in title (71): SomeQuestion‭ (Staging Ground) by some-user on stackoverflow.com

Note: This change might potentially break certain userscripts on those reports?

2023-06-04 07:39 UTC, tripleee commented
An additional complication might be how it affects the logic for forcing the final message to be within the maximum length allowed by the chat API. I'm not in a place where I can investigate that, but I'm noting it for when we can do a proper review.

Thanks for the contribution!

2023-08-16 19:11 UTC, makyen requested changes
This "request changes" review is really "needs verification, with possible needs changes". With Staging Ground currently shut down and empty, I'm unable to verify that `post.post_url` will have a URL which contains the text "staging-ground" (note: "/staging-ground/" would be a better test). The `post.post_url` is derived from the `link` value returned from the SE API for the question. I suspect that what will be supplied by the SE API is the canonical `/questions/<post ID>/...` URL, rather than the staging ground URL.

SD was changed to parse `/staging-ground/<post ID>` URLs, but that seems to have been as a result of my realizing that SD needs to do that in order to accommodate user's providing such URLs in chat commands, rather than as the `link` value returned by the SE API.

If you verified that the `link` value provided by the SE API has "staging-ground" in it prior to submitting this PR, then that's sufficient for this concern.

2023-08-17 20:13 UTC, Papershine commented
I recall verifying with the SE API that they also return a `link` with `staging-ground` in it somewhere, but my memory is hazy about the exact format. Will reconfirm when (or if) Staging Ground is online again.

2023-08-19 06:11 UTC, closed without merging

2024-09-07 11:00 UTC, codygray commented
I wanted to re-open this, but I cannot do so because "The repository that submitted this pull request has been deleted." Instead, I posted [a new issue](https://github.com/Charcoal-SE/SmokeDetector/issues/13136).